### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by enclass** [colmena/colmena-cms#216]
by running nps dev in the `colmena-cms` folder, I get this error:

```$ nps dev
nps executing: nps -p dev.admin,dev.api
nps executing: cd admin; nps dev
nps executing: cd api; nps dev
nps executing: ng serve --port 9000 --host 0.0.0.0 --progress false --hmr -e=hmr
nps executing: NODE_ENV=development nodemon server/server.js --watch common --watch server --ext js,json
~/colmena-cms/admin/node_modules/@angular/cli/models/config/config.js:15
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (~/colmena-cms/admin/node_modules/@angular/cli/models/config.js:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
The script called "dev" which runs "ng serve --port 9000 --host 0.0.0.0 --progress false --hmr -e=hmr" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.1.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "dev.admin" which runs "cd admin; nps dev" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.1.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
/bin/sh: line 1: 20722 Terminated: 15          nps dev
The script called "dev" which runs "nps -p dev.admin,dev.api" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.1.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code```

**Comment by beeman** [comment]
@enclass what version of Node and NPM are you using?

**Comment by enclass** [comment]
@beeman upgrading node to >4.5 fixed the problem, thx
