### ISSUE TITLE
initializing the database with sqlite3-connector gives "path.js:7 TypeError: Path must be a string"

### ISSUE THREAD

**Issue by kumorig** [colmena/colmena-cms#241]
### Bug or feature request

- [X] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
Steps to reproduce:
#### 1) Change `datasources.json` to use sqlite

`  "db"      : {
    "name"      : "db",
    "connector" : "sqlite3",
    "file"      : "pc2sp.db",
    "debug"     : true
  },`
#### 3) Run  `node . --verbose` in apps/api
```
05:17:26.778Z  INFO colmena: User: registration enabled
05:17:26.993Z  INFO colmena: System init db: skipping sample data
(node:6236) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SQLITE_ERROR: no such table: setting
```

#### 4) Run using INITDB=1   `INITDB=1 node . --verbose`
```
05:30:25.323Z  INFO colmena: User: registration enabled
05:30:25.569Z  INFO colmena: Container does not exist, not destroying container default
{ Error: SQLITE_ERROR: table "user" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "acl" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "post" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "product" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "event" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "setting" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "page" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "file" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "accesstoken" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "domain" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "rolemapping" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "role" already exists errno: 1, code: 'SQLITE_ERROR' }
{ Error: SQLITE_ERROR: table "basemodel" already exists errno: 1, code: 'SQLITE_ERROR' }
05:30:26.575Z  INFO colmena: Container does not exist, creating container 1
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received 1
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at FileSystemProvider.createContainer (C:\projects\tmp\colmena-cms\apps\api\node_modules\loopback-component-storage\lib\providers\filesystem\index.js:115:18)
    at StorageService.createContainer (C:\projects\tmp\colmena-cms\apps\api\node_modules\loopback-component-storage\lib\storage-service.js:90:22)
    at Container.getContainer (C:\projects\tmp\colmena-cms\apps\api\common\models\container\container.js:31:28)
    at C:\projects\tmp\colmena-cms\apps\api\node_modules\loopback-component-storage\lib\storage-service.js:118:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
### Link to sample repo to reproduce issue (if bug)
https://github.com/kumorig/colmena-cms/tree/next-sqlite

### Expected result
Expected to not get errors.

### Actual result (if bug)
Errors (!)

### Additional information (OS, Node.js version, etc)
OS: Windows 10 (ugh), Node: 6.10.3 (also tried with 7.10.0)

$ npm -v 
`4.2.0`

$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
`win32 x64 7.10.0`

**Comment by kumorig** [comment]
I found out that 

> The SQLite3 connector does not currently support model discovery.
And
>The SQLite3 connector does not currently support auto-migrate or auto-upgrade

So I believe you can close this. (I switched to https://github.com/Synerzip/loopback-connector-sqlite instead and have no errors as of yet.)

**Comment by beeman** [comment]
@kumorig great find! Glad to hear it's fixed!
